# Generated by Django 5.1.3 on 2024-11-30 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=uuid.UUID('7ac552e9-2c56-45ec-9c63-04f72e211a7d'), max_length=36, unique=True),
        ),
    ]
