# Generated by Django 5.1.3 on 2024-11-30 17:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_token_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField(validators=[api.models.PositiveValidator])),
                ('price', models.IntegerField(validators=[api.models.PositiveValidator])),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
